CREATE TABLE IF NOT EXISTS phone_verification_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(32) NOT NULL,
    verification_code VARCHAR(16) NOT NULL,
    purpose VARCHAR(32) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    consumed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_phone_verification_code_phone ON phone_verification_code(phone_number, purpose, consumed);

ALTER TABLE user_distribution_profile ADD COLUMN IF NOT EXISTS phone_number VARCHAR(32);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_distribution_profile_phone ON user_distribution_profile(phone_number);

ALTER TABLE invite_code_issue_record ADD COLUMN IF NOT EXISTS guild_id VARCHAR(64);
ALTER TABLE invite_code_issue_record ADD COLUMN IF NOT EXISTS guild_name VARCHAR(128);
ALTER TABLE invite_code_issue_record ADD COLUMN IF NOT EXISTS guild_invite_code VARCHAR(64);

ALTER TABLE linky_account_binding ADD COLUMN IF NOT EXISTS expected_guild_id VARCHAR(64);
ALTER TABLE linky_account_binding ADD COLUMN IF NOT EXISTS expected_guild_name VARCHAR(128);
ALTER TABLE linky_account_binding ADD COLUMN IF NOT EXISTS expected_guild_invite_code VARCHAR(64);

CREATE TABLE IF NOT EXISTS guild_account_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(32) NOT NULL,
    inviter_user_id BIGINT,
    guild_id VARCHAR(64) NOT NULL,
    guild_name VARCHAR(128) NOT NULL,
    guild_invite_code VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_guild_account_config_scope ON guild_account_config(product_code, inviter_user_id);
CREATE INDEX IF NOT EXISTS idx_guild_account_config_guild ON guild_account_config(product_code, guild_id);

INSERT INTO guild_account_config(product_code, inviter_user_id, guild_id, guild_name, guild_invite_code, enabled)
SELECT 'LINKY', NULL, 'LINKY_DEFAULT_GUILD', 'Linky Official Guild', 'JOIN-LINKY', TRUE
WHERE NOT EXISTS (SELECT 1 FROM guild_account_config WHERE product_code = 'LINKY' AND inviter_user_id IS NULL);
