CREATE TABLE linky_webhook_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    linky_order_id VARCHAR(80) NOT NULL,
    source_event_id VARCHAR(80) NULL,
    user_id BIGINT NOT NULL,
    income_amount DECIMAL(18,6) NOT NULL,
    currency_code VARCHAR(10) NOT NULL,
    paid_at DATETIME NOT NULL,
    request_received_at DATETIME NOT NULL,
    linky_timestamp VARCHAR(64) NULL,
    linky_signature VARCHAR(255) NULL,
    internal_token_status VARCHAR(32) NOT NULL,
    signature_status VARCHAR(32) NOT NULL,
    replay_status VARCHAR(32) NOT NULL,
    request_status VARCHAR(32) NOT NULL,
    failure_reason VARCHAR(255) NULL,
    request_ip VARCHAR(64) NULL,
    payload_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_linky_webhook_order_received (linky_order_id, request_received_at),
    INDEX idx_linky_webhook_user_received (user_id, request_received_at),
    INDEX idx_linky_webhook_status_received (request_status, request_received_at)
);
